### ISSUE TITLE
Morning session spooky day

### ISSUE THREAD

**Issue by Fig77** [Fig77/Gradients-Project#3]
Morning session 31/10

**Comment by tcc7130** [comment]
Good things:
- Looks really nice
- Folder organization
- Classes for everything (CSS)

Bad things:
- Too many branches

**Comment by TashfeenRao** [comment]
It looks good keep working.
code is organized.
css styling is great.

friendly suggestion.
try to remove flex-direction row.

**Comment by Rhelli** [comment]
- Your header as a property of 'align-items: center' on it, causing everything to spawn from the middle of the page and move outwards. Thats why your navbar is out of place.

- Solutions: (a) Change the header's 'align-items' property to 'flex-start' (and increase the text margin/padding to accomadate this change); (b) place the navbar before the header element itself so it is at the top of the page; (c) Apply an absolute position to the navbar with 'top: 0; left: 0; right: 0;' (a solution but not recommended).

- Navbar needs to have a width of '100vw' / '100%' vs the fixed width it has at the moment to fill out the screen.

- Your border style on your navbar can be condensed down to one line of code. E.g. 'border: 2px solid #EEEEE;'

- Try using the '::after'' for your search bar so you can change the length once it  it expands.

Otherwise, a very solid looking project! Gradients look great and the search bar extension looks really good!
